import type { Language } from "@/lib/content";

export const authCopy = {
  en: {
    brand: "HARON OS",
    loginTitle: "Welcome back",
    signupTitle: "Create your HARON OS account",
    forgotTitle: "Reset your password",
    resetTitle: "Choose a new password",
    verifyTitle: "Verify your email",
    profileTitle: "Profile command center",
    accountTitle: "Account settings",
    securityTitle: "Security settings",
    subtitle: "Secure Firebase authentication, synced profile data, and a premium bilingual AI workspace.",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm password",
    name: "Full name",
    username: "Username",
    bio: "Bio",
    remember: "Remember me",
    login: "Login",
    signup: "Create account",
    google: "Continue with Google",
    guest: "Continue as guest",
    forgot: "Forgot password?",
    noAccount: "New to HARON OS?",
    hasAccount: "Already have an account?",
    sendReset: "Send reset link",
    updatePassword: "Update password",
    resend: "Resend email",
    checking: "Checking verification",
    verified: "Email verified. Redirecting...",
    save: "Save changes",
    upload: "Upload avatar",
    logout: "Logout",
    dashboard: "Dashboard",
    settings: "Settings",
    security: "Security",
    billing: "Billing",
    profile: "Profile",
    loading: "Securing session...",
    resetSent: "Password reset email sent. Check your inbox.",
    verificationSent: "Verification email sent.",
    saved: "Changes saved.",
    passwordsMismatch: "Passwords do not match.",
    weakPassword: "Use at least 6 characters.",
    completeFields: "Please complete all required fields.",
    protectedRedirect: "Redirecting you to login...",
  },
  ar: {
    brand: "هارون أو إس",
    loginTitle: "حياك من جديد",
    signupTitle: "أنشئ حسابك في هارون أو إس",
    forgotTitle: "استعادة كلمة المرور",
    resetTitle: "اختر كلمة مرور جديدة",
    verifyTitle: "تأكيد البريد الإلكتروني",
    profileTitle: "مركز الملف الشخصي",
    accountTitle: "إعدادات الحساب",
    securityTitle: "إعدادات الأمان",
    subtitle: "تسجيل دخول آمن عبر Firebase، ملف شخصي متزامن، وتجربة ذكاء اصطناعي فاخرة بثنائية اللغة.",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    name: "الاسم الكامل",
    username: "اسم المستخدم",
    bio: "نبذة",
    remember: "تذكرني",
    login: "دخول",
    signup: "إنشاء حساب",
    google: "المتابعة بجوجل",
    guest: "الدخول كضيف",
    forgot: "نسيت كلمة المرور؟",
    noAccount: "جديد على هارون؟",
    hasAccount: "عندك حساب؟",
    sendReset: "إرسال رابط الاستعادة",
    updatePassword: "تحديث كلمة المرور",
    resend: "إعادة الإرسال",
    checking: "جاري التحقق",
    verified: "تم تأكيد البريد. بنحوّلك الآن...",
    save: "حفظ التغييرات",
    upload: "رفع صورة",
    logout: "تسجيل الخروج",
    dashboard: "لوحة التحكم",
    settings: "الإعدادات",
    security: "الأمان",
    billing: "الفوترة",
    profile: "الملف الشخصي",
    loading: "جاري تأمين الجلسة...",
    resetSent: "تم إرسال رابط الاستعادة. شيّك بريدك.",
    verificationSent: "تم إرسال رسالة التحقق.",
    saved: "تم حفظ التغييرات.",
    passwordsMismatch: "كلمتا المرور غير متطابقتين.",
    weakPassword: "استخدم 6 أحرف على الأقل.",
    completeFields: "كمّل الحقول المطلوبة.",
    protectedRedirect: "بنحوّلك لتسجيل الدخول...",
  },
} as const satisfies Record<Language, Record<string, string>>;

export function createUsernameSeed(email: string | null, name?: string | null) {
  const source = name?.trim() || email?.split("@")[0] || "haron-user";
  return source
    .toLowerCase()
    .replace(/[^a-z0-9._-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 28);
}
